{"name": "test_access_points_connectivity", "status": "passed", "description": "Test case to verify Access Points Connectivity", "attachments": [{"name": "Access Point Connectivity Failed", "source": "59930c13-6172-4640-9844-f5119a467cc8-attachment.attach"}, {"name": "Manager status is Active", "source": "78e4b391-9ad0-4669-a2bf-2d5eab7a53ec-attachment.attach"}, {"name": "log", "source": "603efa9c-348a-408d-8b65-7a11c97638ae-attachment.txt", "type": "text/plain"}], "start": 1627086559690, "stop": 1627086559690, "uuid": "47dd9807-8935-4554-8d8c-bf57ca42729f", "historyId": "9c9c1794599fbd8dfa1d00f937bef4d8", "testCaseId": "b1de51dd692b456a6a233ecea89ec452", "fullName": "test_connectivity.TestResources#test_access_points_connectivity", "labels": [{"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_test_run')"}, {"name": "tag", "value": "sanity_55"}, {"name": "tag", "value": "test_access_points_connectivity"}, {"name": "tag", "value": "test_resources"}, {"name": "suite", "value": "test_connectivity"}, {"name": "subSuite", "value": "TestResources"}, {"name": "host", "value": "testing-89-r7ptb"}, {"name": "thread", "value": "6-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_connectivity"}], "links": [{"type": "test_case", "name": "test_access_points_connectivity"}, {"type": "test_case", "name": "Test Resources"}]}