{"name": "test_firmware_upgrade_status_gateway", "status": "broken", "statusDetails": {"message": "NameError: Invalid response code.", "trace": "self = <tests.test_connectivity.TestFMS object at 0x7fac3fe587f0>\nget_apnos = <class 'apnos.apnos.APNOS'>\nget_configuration = {'access_point': [{'Backup Location': '', 'Backup Password': '', 'Backup Type': 'File System', 'Backup User': '', ...}...-Station-Name': 'wlan0', '5G-Radio': ['1.1.wiphy1, 1.1.wiphy3'], '5G-Station-Name': 'wlan1', ...}, 'name': 'lanforge'}}\nsetup_controller = <controller.controller_2x.controller.Controller object at 0x7fac400f39a0>\nget_ap_logs = None\n\n    @pytest.mark.test_firmware_gw\n    def test_firmware_upgrade_status_gateway(self, get_apnos, get_configuration, setup_controller, get_ap_logs):\n        status = []\n        for ap in get_configuration['access_point']:\n            ap_ssh = get_apnos(ap, pwd=\"../libs/apnos/\", sdk=\"2.x\")\n            ap_version = ap_ssh.get_ap_version_ucentral()\n            current_version_ap = str(ap_version).split()\n>           data = setup_controller.get_device_by_serial_number(serial_number=ap['serial'])\n\ntest_connectivity.py:155: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../libs/controller/controller_2x/controller.py:173: in get_device_by_serial_number\n    self.check_response(\"GET\", resp, self.make_headers(), \"\", uri)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <controller.controller_2x.controller.Controller object at 0x7fac400f39a0>\ncmd = 'GET', response = <Response [404]>\nheaders = {'Authorization': 'Bearer d1f7c44fa7aaf4d18bb38b9ec1298831a73908dea3f93aa54ebadfa48a7fcab9', 'Connection': 'keep-alive', 'Keep-Alive': 'timeout=10, max=1000'}\ndata_str = ''\nurl = 'https://gw-32950f48.cicd.lab.wlan.tip.build:16002/api/v1/device/903cb39d6918'\n\n    def check_response(self, cmd, response, headers, data_str, url):\n        if response.status_code >= 400:\n            if response.status_code >= 400:\n                print(\"check-response: ERROR, url: \", url)\n            else:\n                print(\"check-response: url: \", url)\n            print(\"Command: \", cmd)\n            print(\"response-status: \", response.status_code)\n            print(\"response-headers: \", response.headers)\n            print(\"response-content: \", response.content)\n            print(\"headers: \", headers)\n            print(\"data-str: \", data_str)\n    \n        if response.status_code >= 400:\n            # if True:\n>           raise NameError(\"Invalid response code.\")\nE           NameError: Invalid response code.\n\n../libs/controller/controller_2x/controller.py:153: NameError"}, "start": 1637528575340, "stop": 1637528578273, "uuid": "96ff643e-85be-4d7c-9fe8-2bf1227faed4", "historyId": "9317dff433bd6cfcbbbf4023245d7067", "testCaseId": "9083a4c43940d88d440139b6c4f5411e", "fullName": "test_connectivity.TestFMS#test_firmware_upgrade_status_gateway", "labels": [{"name": "tag", "value": "uc_firmware"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "uc_sanity"}, {"name": "tag", "value": "test_resources"}, {"name": "tag", "value": "test_firmware_gw"}, {"name": "tag", "value": "sanity_55"}, {"name": "suite", "value": "test_connectivity"}, {"name": "subSuite", "value": "TestFMS"}, {"name": "host", "value": "testing-83-zpr9c"}, {"name": "thread", "value": "379-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_connectivity"}], "links": [{"type": "test_case", "name": "Firmware Management"}]}