{"uuid": "6aab4149-454c-4509-8a79-1c71392129d3", "children": ["b1f19a1a-e94c-4548-84ec-3abf4ec2dfe1", "6860c80d-9b3a-4609-8ef7-63e1b4cad8c2", "5d16fe1e-f449-4bfa-899f-a9d9648b45ef", "a76c00b6-2919-40c5-ab12-8e3b1e6998cc", "e9801556-ca69-4570-9745-65a413375ef1", "ed2ef2ef-b5fa-40f2-a1eb-b644049d464b"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'output' referenced before assignment\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 515, in setup_profiles\n    connected, latest, active = ap_ssh.get_ucentral_status()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 340, in get_ucentral_status\n    if output.__contains__(b'\"connected\":'):\n"}, "start": 1637701613759, "stop": 1637701645714}], "start": 1637701613759, "stop": 1637701651949}