{"uuid": "696e436b-99c0-450b-ad32-d090716563ad", "children": ["acec7ce1-1ae5-41dc-95e7-775ac2b75e88", "a0ddd612-932f-4955-991d-d93d5ba8b73b", "43e76a4e-fbde-4d3b-b536-5c8935a2df01", "770b6a46-3939-4081-8402-bd68777562da", "a418329a-3e8a-4bec-8b95-374cdd905a26", "736ff2e3-9804-41b3-b081-ef67ba06c5d4"], "befores": [{"name": "setup_profiles", "status": "failed", "statusDetails": {"message": "Failed: AP latest and active are different\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 531, in setup_profiles\n    pytest.fail(\"AP latest and active are different\")\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/outcomes.py\", line 153, in fail\n    raise Failed(msg=msg, pytrace=pytrace)\n"}, "attachments": [{"name": "Active Config: ", "source": "d1f43d9b-d206-42bc-afcd-4df8ca5b9dc0-attachment.attach"}, {"name": "Latest Config: ", "source": "88129863-8939-4a8a-9362-4e8914f07661-attachment.attach"}, {"name": "FAILURE: AP Logs: ", "source": "43e41652-f210-41b6-bcdc-6eb3e1c28c57-attachment.attach"}], "start": 1636147072918, "stop": 1636147396184}], "start": 1636147072918, "stop": 1636147397930}