{"name": "test_ToogleWifiMode_5g_WPA[setup_profiles0]", "status": "broken", "statusDetails": {"message": "TypeError: object of type 'TypeError' has no len()", "trace": "def teardown():\n        try:\n            print(\"\\n\\n---------- Tear Down ----------\")\n            testFailed = request.session.testsfailed\n            if testFailed>0:\n                print (\"Test Case Failure, please check report link: \" + testCaseName)\n                exceptionFailure = request.config.cache.get(\"SelectingWifiFailed\", None)\n>               reporting_client.test_stop(TestResultFactory.create_failure(exceptionFailure))\n\n../libs/perfecto_libs/android_lib.py:122: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nreason = None, traceback = None, failureReason = None\n\n    @staticmethod\n    def create_failure(reason, traceback=None, failureReason=None):\n>       return TestResultFailure(reason, traceback, failureReason)\n\n/usr/local/lib/python3.8/site-packages/perfecto/test/TestResultFactory.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <perfecto.test.TestResult.TestResultFailure object at 0x7efe743de730>\nreason = None, exception = None, failureReason = None\n\n    def __init__(self, reason, exception=None, failureReason=None):\n    \n        if exception is not None:\n            self.message = str(reason) + ': ' + str(exception)\n        else:\n            self.message = reason\n    \n>       if len(self.message) > 4096:\nE       TypeError: object of type 'NoneType' has no len()\n\n/usr/local/lib/python3.8/site-packages/perfecto/test/TestResult.py:32: TypeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <allure_commons._allure.fixture object at 0x7efe743de5b0>, args = ()\nkwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n/usr/local/lib/python3.8/site-packages/allure_commons/_allure.py:200: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../libs/perfecto_libs/android_lib.py:142: in teardown\n    reporting_client.test_stop(TestResultFactory.create_failure(e))\n/usr/local/lib/python3.8/site-packages/perfecto/test/TestResultFactory.py:11: in create_failure\n    return TestResultFailure(reason, traceback, failureReason)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <perfecto.test.TestResult.TestResultFailure object at 0x7efe862d1610>\nreason = TypeError(\"object of type 'NoneType' has no len()\"), exception = None\nfailureReason = None\n\n    def __init__(self, reason, exception=None, failureReason=None):\n    \n        if exception is not None:\n            self.message = str(reason) + ': ' + str(exception)\n        else:\n            self.message = reason\n    \n>       if len(self.message) > 4096:\nE       TypeError: object of type 'TypeError' has no len()\n\n/usr/local/lib/python3.8/site-packages/perfecto/test/TestResult.py:32: TypeError"}, "parameters": [{"name": "setup_profiles", "value": "{'mode': 'NAT', 'ssid_modes': {'wpa': [{'ssid_name': 'ssid_wpa_2g', 'appliedRadios': ['is2dot4GHz'], 'security_key': 'something', 'profile_name': 'interop-SSID-wpa-0-NAT', 'mode': 'NAT', 'vlan': 1}, {'ssid_name': 'ssid_wpa_5g', 'appliedRadios': ['is5GHzU', 'is5GHz', 'is5GHzL'], 'security_key': 'something', 'profile_name': 'interop-SSID-wpa-1-NAT', 'mode': 'NAT', 'vlan': 1}], 'wpa2_personal': [{'ssid_name': 'ssid_wpa2_2g', 'appliedRadios': ['is2dot4GHz'], 'security_key': 'something', 'profile_name': 'interop-SSID-wpa2_personal-0-NAT', 'mode': 'NAT', 'vlan': 1}, {'ssid_name': 'ssid_wpa2_5g', 'appliedRadios': ['is5GHzU', 'is5GHz', 'is5GHzL'], 'security_key': 'something', 'profile_name': 'interop-SSID-wpa2_personal-1-NAT', 'mode': 'NAT', 'vlan': 1}]}, 'rf': {}, 'radius': False}"}], "start": 1627005530537, "stop": 1627005647119, "uuid": "277dffe4-0821-4e2c-8b0a-ddc6fb7335df", "historyId": "af8534f7219e280888993892260861c2", "testCaseId": "3a0bafca00ae76120289dae6d9b46983", "fullName": "e2e.interOp.android.WifiMode.test_ToggleWifiMode.TestToggleWifiMode#test_ToogleWifiMode_5g_WPA", "labels": [{"name": "feature", "value": "NAT MODE CLIENT CONNECTIVITY"}, {"name": "tag", "value": "wpa"}, {"name": "tag", "value": "fiveg"}, {"name": "tag", "value": "interop"}, {"name": "tag", "value": "android"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_profiles')"}, {"name": "tag", "value": "ToggleWifiMode"}, {"name": "tag", "value": "interop_and"}, {"name": "parentSuite", "value": "e2e.interOp.android.WifiMode"}, {"name": "suite", "value": "test_ToggleWifiMode"}, {"name": "subSuite", "value": "TestToggleWifiMode"}, {"name": "host", "value": "interop-ci-77-android-bjg9l"}, {"name": "thread", "value": "6-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "e2e.interOp.android.WifiMode.test_ToggleWifiMode"}]}