{"uuid": "e167e214-9c77-4bd4-856d-9c9fcfa32790", "children": ["c977cf8e-7aea-4f46-bb8f-cb397e6ef98a", "58f1329e-8e6f-4dc9-b46a-407c1cbd7fd8"], "befores": [{"name": "firmware_upgrade", "status": "broken", "statusDetails": {"message": "TypeError: setup_firmware() takes 1 positional argument but 3 were given\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/conftest.py\", line 676, in firmware_upgrade\n    upgrade_status = fixtures_ver.setup_firmware(get_apnos, get_configuration)\n"}, "start": 1639441634541, "stop": 1639441634541}], "start": 1639441634541, "stop": 1639441643139}