{"uuid": "3f971cfe-9694-4f2b-9559-7deb6d276fca", "children": ["b37a4e2a-cc1e-4881-9c8e-2b4b2f56cb01", "e5b07ecd-f7fb-4fe5-a369-2f66b94bffd0"], "befores": [{"name": "setup_profiles", "status": "failed", "statusDetails": {"message": "Failed: AP latest and active are different\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/advanced/conftest.py\", line 87, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 565, in setup_profiles\n    pytest.fail(\"AP latest and active are different\")\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/outcomes.py\", line 153, in fail\n    raise Failed(msg=msg, pytrace=pytrace)\n"}, "attachments": [{"name": "Active Config: ", "source": "87a6af4c-235c-443b-b875-8a244d1f1824-attachment.attach"}, {"name": "Latest Config: ", "source": "d635aaf4-b9b9-4c15-9e93-c0655fa744ae-attachment.attach"}, {"name": "FAILURE: AP Logs: ", "source": "9872530c-65bc-4de3-9fba-b0f19ddaa476-attachment.attach"}], "start": 1638478239054, "stop": 1638478567638}], "start": 1638478239054, "stop": 1638478568040}