{"uuid": "571ee4df-c648-4160-a848-00265c5a4e8b", "children": ["b93f9226-09ef-4c60-a903-b867dcda8067", "bc68a450-600a-41fd-a610-41864462068a", "e4990fb5-2534-471c-ad2b-b10a5f317d2b", "39a1cc80-11cb-4253-ad8e-752d633d473e", "0a47ced4-9277-4ec7-8ca1-4d010248b69f"], "befores": [{"name": "setup_profiles", "status": "failed", "statusDetails": {"message": "Failed: AP latest and active are different\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/advanced/conftest.py\", line 87, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 532, in setup_profiles\n    pytest.fail(\"AP latest and active are different\")\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/outcomes.py\", line 153, in fail\n    raise Failed(msg=msg, pytrace=pytrace)\n"}, "attachments": [{"name": "Active Config: ", "source": "3e53aad1-0fb9-48ba-abd2-6c2e07143df7-attachment.attach"}, {"name": "Latest Config: ", "source": "1e446ab0-9723-43ee-ac34-251dfa2d684b-attachment.attach"}, {"name": "FAILURE: AP Logs: ", "source": "95143142-1955-4181-b2c0-e7c00992180c-attachment.attach"}], "start": 1638045848087, "stop": 1638046176804}], "start": 1638045848087, "stop": 1638046178289}