{"uuid": "bef94fdc-0666-4ee0-be8e-2f0cbcd913a0", "children": ["fa0edceb-1549-40c1-a361-22d42b8fad73", "007b617e-96d7-4348-85e7-cd555abe09db", "31ae0c59-3779-4cd4-9531-8602007d46b0", "ab970442-11cc-4d9c-8345-3b654490329f", "f956dbaa-b880-42d8-841b-16545ab67212", "b4234b33-d3a1-4ed8-bf96-002442778070"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "NameError: Invalid response code.\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 543, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_ref[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 563, in push_config\n    self.sdk_client.check_response(\"POST\", resp, self.sdk_client.make_headers(), basic_cfg_str, uri)\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 153, in check_response\n    raise NameError(\"Invalid response code.\")\n"}, "attachments": [{"name": "ucentral_config: ", "source": "2f5f5f93-2fac-49e8-a6d3-47c72b202435-attachment.json", "type": "application/json"}, {"name": "/configure response: 400", "source": "3c2a0376-3e27-4536-981c-187183f47e41-attachment.json", "type": "application/json"}], "start": 1637355723717, "stop": 1637355729169}], "start": 1637355723717, "stop": 1637355731132}